### ISSUE TITLE
ch6-1의 코드로 크롤링을 하면 빈 값으로 저장되어 수정이 필요해 보입니다.

### ISSUE THREAD

**Issue by coninggu** [wikibook/python-for-web-scraping#2]
안녕하세요. 
프로그래밍 Q&A와 관련한 작은 커뮤니티를 운영하고 있습니다.

해당 커뮤니티에 질문사항으로 ch6-1의 코드를 실행하면 빈값으로 저장된다는 질문이 등록되어 확인해보니 https://blog.scrapinghub.com 사이트의 HTML이 예제코드와 다르게 변경되어 있어 수정한 답변을 등록하였습니다.
그리고 이곳의 소스코드도 수정이 필요할 것으로 보여 이슈로 등록합니다.

아래는 질문한 사이트입니다.
http://dolgo.net/tag/python/question/275
참고하시라 남기고 갑니다.

**Comment by wikibook** [comment]
@coninggu 안녕하세요. 위키북스입니다. 말씀하신 내용을 해당 책의 역자분께 전달했고, 그대로 반영하면 된다고 답신을 받았습니다. 정오표 내용은 각각 홈페이지와 예제 코드에도 반영했습니다. 좋은 하루 보내세요. 감사합니다.

- <https://wikibook.co.kr/python-for-web-scraping/>
- <https://github.com/wikibook/python-for-web-scraping/>
